### ISSUE TITLE
Breaking Changes with 0.9.X versions

### ISSUE THREAD

**Issue by ChristianIvicevic** [shikijs/shiki#124]
My deployment pipeline luckily noticed some undocumented breaking changes since `loadTheme` now returns a promise instead of the theme and unecpectedly loading a custom theme no longer starts at the correct root directory. The following snippet used to work in v0.2.X:
```typescript
const highlighter = await getHighlighter({
  theme: loadTheme('./constants/shiki-themes/one-dark-pro.json'),
});
```
After reviewing the error message I expected this to work:
```typescript
const highlighter = await getHighlighter({
  theme: await loadTheme('./constants/shiki-themes/one-dark-pro.json'),
});
```
Unfortunately my custom theme from the JSON file is not located as the shiki folder is being considered the root folder resulting in the following message:
```
Error: ENOENT: no such file or directory, open '/Code/personal/deployonfriday.io/node_modules/shiki/constants/shiki-themes/one-dark-pro.json'
```
I had to adjust the path to get out of the shiki folder: `../../constants/shiki-themes/one-dark-pro.json`.

I understand that this library isn't released in a v1.X yet, but documenting such significant breaking changes would be nice for the future as I really like this library a lot.

**Comment by antfu** [comment]
The changes to the async return are documented here https://github.com/shikijs/shiki/pull/109, where we forget to copy them into CHANGELOG.md I think. For the path changes, sorry as I forget to mention about. Since Shiki is now isomorphic, which means files could be loaded from either Node.js or browser, you can use `path.resolve` passing the absolute path to it.
