### ISSUE TITLE
Performance doubled between 0.9.3 and 0.9.5

### ISSUE THREAD

**Issue by orta** [shikijs/shiki#169]
Timing for the test suite for Shiki Twoslash doubled when we updated (and then reverted with 
https://github.com/shikijs/twoslash/pull/38/commits/e30e47e0d7bc9dcd2283dd317a9d9b1054942e60 )

I don't have time for a look why, but just raising incase there's something obvious

**Comment by octref** [comment]
Was there a misconfiguration on your side? I run pnpm test with both 0.9.3 and 0.9.5, and they took roughly the same time (7s).

Test Suites: 8 passed, 8 total
Tests:       39 passed, 39 total
Snapshots:   7 passed, 7 total
Time:        6.013 s

Test Suites: 8 passed, 8 total
Tests:       39 passed, 39 total
Snapshots:   7 passed, 7 total
Time:        6.02 s
Ran all test suites.

**Comment by riasvdv** [comment]
I'm having a similar issue. Running the following script with node:

```js
shiki.getHighlighter({
    theme: 'nord',
}).then((highlighter) => {
    process.stdout.write(highlighter.codeToHtml('console.log(\"Hello world\")', 'js'));
});
```
Takes ~880ms on 0.9.3 and ~3s on 0.9.5

If I call `getLoadedLanguages` on 0.9.5, all languages seem to be loaded, is this intended? I can't see which languages are loaded on 0.9.3 as the function isn't available there

**Comment by orta** [comment]
Yeah, looking at this again, after updating a second time https://github.com/shikijs/twoslash/pull/104

Before:

```
PASS packages/shiki-twoslash/test/twoslash-renderer.test.ts (7.515 s)
PASS packages/remark-shiki-twoslash/test/fixtures.test.ts (15.383 s)
```

After:

```
PASS packages/shiki-twoslash/test/twoslash-renderer.test.ts (12.045 s)
FAIL packages/remark-shiki-twoslash/test/fixtures.test.ts (26.313 s)
```

**Comment by Gerrit0** [comment]
Spent a bit of time looking at this, and I can claim fairly confidently that 0.9.8 is slower than 0.9.3, though I'm not seeing times double.

```js
const { performance } = require("perf_hooks")
const shiki = require("shiki")
const fs = require("fs")
const { join } = require("path")
const code = fs.readFileSync(join(__dirname, "node_modules/shiki/dist/index.js"), "utf-8")

async function main() {
    const start = performance.now();
    const highlighter = await shiki.getHighlighter({ theme: "nord" });

    for (let i = 0; i < 100; i++) {
        highlighter.codeToHtml(code, "js")
    }

    const end = performance.now();
    console.log(`Finished in ${end - start}ms`)
}

main().catch(err => {
    console.error(err);
    process.exitCode = 1
})
```

With Shiki 0.9.3:
Finished in 71207.78589999676ms

With Shiki 0.9.8:
Finished in 104856.62179994583ms

Node: v14.15.4

**Comment by Gerrit0** [comment]
According to a flamegraph, the extra time appears to be in "wasm-function[107]"... given that the only wasm in Shiki is the regex library. I suspect that the root cause of this is some regex in the tokenizer being changed to a less performant version.

I realized some time after posting the above that the comparison was unfair since the Shiki source changed. I switched to using the attached file... and now 0.9.8 takes half the time that 0.9.3 does!

[code.txt](https://github.com/shikijs/shiki/files/7072857/code.txt)

**Comment by Gerrit0** [comment]
Alright, with much more time spent.... I really can't reproduce this at all.

I ran tests on about a dozen cases, including the trivial example above, Shiki's 0.9.8 source, Shiki's 0.9.3 source, several other 1000+ line files picked from my node_modules folder, and a 1600 line file that looked like:

```js
console.log("Hello world")
console.log("Hello world")
console.log("Hello world")
...
```

In every case, version 0.9.8 was consistently at least 20% faster than 0.9.3 when measuring the performance of `codeToHtml`

However, version 0.9.8 is slightly slower at initially loading the theme. I set up a benchmark to load the "nord" them 1000 times.
v0.9.3: 52.6 sec
v0.9.8: 69.0 sec

However... this doesn't seem like it would be responsible for the slowdown that orta was seeing, since any re-use of a highligher shouldn't require reloading it thousands of times anyways. If anyone has some additional information that might help track this down, it would be greatly appreciated!

**Comment by frencojobs** [comment]
Shiki over 0.9.3 has become unusable for me because of this. I'm not entirely sure but I think the performance also depends on NodeJS version and mostly on OS. Here's what I found from my GitHub Actions.

## For Node 12

<table>
<tr>
	<td> Shiki Version
	<td> Node 12 Latest Windows
	<td> Node 12 Latest Ubuntu
	<td> Node 12 Latest MacOS
<tr>
	<td> 0.9.3
	<td> 4s
	<td> 3s
	<td> 4s
<tr>
	<td> ^0.9.8
	<td> <b>81s</b> (Unusable)
	<td> 9s
	<td> 11s
</table>

## For Node 14

<table>
<tr>
	<td> Shiki Version
	<td> Node 14 Latest Windows
	<td> Node 14 Latest Ubuntu
	<td> Node 14 Latest MacOS
<tr>
	<td> 0.9.3
	<td> 4s
	<td> 4s
	<td> 4s
<tr>
	<td> ^0.9.8
	<td> 9s
	<td> 8s
	<td> 10s
</table>

This is the code used.

```ts
let highlighter: shiki.Highlighter
beforeAll(async () => (highlighter = await shiki.getHighlighter({})), 10e3)
```

**Comment by orta** [comment]
Interesting, that's not even doing syntax highlighting - just booting up. Running on today's HEAD, if you run just `shiki.getHighlighter` we load 148 grammars into memory- in 0.9.3 it loads 129. Not particularly drastic between them. 

We did switch to JSON5 from looking at [the diff](https://github.com/shikijs/shiki/compare/v0.9.3...v0.9.5) (and now have switched to vscode-jsonc) - (so if you can re-run with 0.9.11 that'd be awesome)

Either way, we are loading all grammars into memory during `shiki.getHighlighter` (because that's the async bit) which means we can safely synchronously access grammars inside the highlighting. 

Regardless of whether this is fixed by the JSON parser switch, I think we should have a separate _node-only_ synchronous code path for getting the grammar only when it is needed. Which means `shiki.getHighlighter` registers the languages exists, but doesn't load a grammar until it is requested by a code sample. This should reduce the amount of work needed a bunch for nearly all cases on node.

**Comment by orta** [comment]
I've updated https://github.com/shikijs/shiki/issues/169#issuecomment-892494781 with the results of running with `0.9.11` - which seem pretty good to me

**Comment by orta** [comment]
Grabbing and setting up the grammars at runtime is not possible without making `highlighter.codeToHtml` async because all of the underlaying textmate grammar APIs [from vscode-textmate](https://github.com/microsoft/vscode-textmate/blob/a53ae3c12bef5499a7dc548b3058ee64bfcbd222/src/main.ts#L71-L168) are async.

**Comment by octref** [comment]
Is this still an issue in the latest version?

**Comment by maccman** [comment]
Also curious?

**Comment by antfu** [comment]
It shouldn't be an issue anymore with 1.0 #557
