### ISSUE TITLE
What Settings can ensure the highest performance？

### ISSUE THREAD

**Issue by zhenguanqing** [shikijs/shiki#197]
I only want to use the simplest features to ensure a smooth experience

**Comment by octref** [comment]
When using `getHighlither`, only specify the themes/languages you want to use.

**Comment by Gerrit0** [comment]
Since I've made a few of these mistakes:

1. You should only ever call `getHighlighter` once. If you need more than one theme, you can use `hl.loadTheme`, or specify all the themes you need up front. `hl.loadLanguage` is the equivalent for grammars.
2. If using `codeToThemedTokens` specify `{ includeExplanation: false }` for the options. This can save a significant portion of the time that it takes to highlight since Shiki won't re-do work to try to give you an explanation for why each token has the color that it does (I'd kind of like to get rid of this option and just never do that work, I'm not sure the explanation is actually useful... have never needed it)

**Comment by aarondfrancis** [comment]
I use the explanations quite heavily, please don't remove them!

**Comment by muenzpraeger** [comment]
Closing as the information is documented in the README.
