### ISSUE TITLE
dark_plus theme colors braces black

### ISSUE THREAD

**Issue by Gerrit0** [shikijs/shiki#45]
Not much else to say... This also seems to happen with dark_vs. I spent a bit of time digging into it, but haven't figured out the fix.

![image](https://user-images.githubusercontent.com/19329837/86496191-714eda00-bd39-11ea-9543-5db4d2d87967.png)

**Comment by Enter-tainer** [comment]
![image](https://user-images.githubusercontent.com/25521218/89770088-cfd55800-db30-11ea-8c6e-82839bfbd0ac.png)

Also facing this issue

**Comment by Enter-tainer** [comment]
It may result from wrong theme configuration. Since source code in dark mode should be white by default, I've add this rule to `dark_vs.json`. And then the braces becomes white.
```json
		{
			"scope": "source",
			"settings": {
				"foreground": "#FFFFFF",
			}
		},
```

![image](https://user-images.githubusercontent.com/25521218/89992506-ece86300-dcb7-11ea-9552-1bb5b8334c5f.png)
![image](https://user-images.githubusercontent.com/25521218/89992516-f2de4400-dcb7-11ea-8c88-e947de26eae7.png)

**Comment by octref** [comment]
@Enter-tainer Yeah, now I remember...VS Code has its default color, but those are not written in themes.
https://github.com/microsoft/vscode/blob/f7f05dee53fb33fe023db2e06e30a89d3094488f/src/vs/platform/theme/common/colorRegistry.ts#L176

I'll need to remember this, when I'm automating pulling themes from upstream.

**Comment by vinkla** [comment]
I'm sorry for writing in a closed issue but I'm seeing this with the `github-dark` theme as well. What can I do to help out fixing this?

![image](https://user-images.githubusercontent.com/499192/97705283-1ee9b400-1ab4-11eb-98f5-19d394ebb89a.png)

**Comment by octref** [comment]
@vinkla See #100 which will be fixed in next ver.
