### ISSUE TITLE
Highlight support for add/delete/focus lines

### ISSUE THREAD

**Issue by codechips** [shikijs/shiki#74]
Not sure if it's possible to highlight lines in Shiki. Haven't found any info in the code and repo. However, while searching for the solution, I accidentally saw that @dceddia already did all the hard work. @dceddia can you please a PR for this? :pray: 

https://github.com/dceddia/shiki-core

**Comment by dceddia** [comment]
Indeed! I've been meaning to make a PR for this and a few other things I changed/fixed - although it looks like a few have already been fixed by other folks! (#66 to fix `&` encoding, #51 & #52 for performance). So I'll have to merge those with mine and make sure nothing broke.

FYI the /shiki-core repo I have (along with shiki-languages and shiki-themes) are just so that I can install these packages in package.json without having to publish them to NPM. I couldn't find a way around the Lerna setup that would allow Netlify to install everything, so I split them up. The source of the changes are (now) in https://github.com/dceddia/shiki

**Comment by octref** [comment]
One thing I'm not sure is whether the metadata for "which line should be highlighted" should live along the source (such as  Markdown) or in code. There are other non-markdown cases which I want to support as well. It seems impossible to find a way to mark highlighted lines in the source for all languages.

Here's vuepress's handling of MD: https://v1.vuepress.vuejs.org/guide/markdown.html#line-highlighting-in-code-blocks

**Comment by dceddia** [comment]
Yeah, where to put the metadata was one of the tricky things to figure out. I handed that responsibility to my own blog code, which parses the code blocks and looks for comments that say which lines to highlight ([see this gist](https://gist.github.com/dceddia/d1d81e832989b3362a17a72b35184ddf)) (my blog uses Jekyll, and integrating it with Shiki took some hackery with sending code over pipes... so that's not all of the code, just the part that parses out the line numbers)

The changes I made to Shiki allow it to accept arrays of line numbers to highlight, so it's sort of format-agnostic in that sense -- it's up to the caller of `codeToHtml` to figure out how to parse out which lines to highlight, and Shiki is just given the plain unannotated code. Here's [an example of it in action](https://daveceddia.com/react-confirmation-modal-state-machine/) and here's one of the code blocks from the markdown:

```js
// focusLines: ['7-20']
// deleteLines: [9]
// addLines: [8]
const confirmationFlow = createMachine(
  /* ... */
  confirming: state(
    transition('confirm', 'loading'),
    transition('cancel', 'initial')
  ),
  loading: invoke(
    (context, event) => context.onCommit(context, event),
    deleteSometing,
    transition('done', 'initial'),
    transition(
      'error',
      'confirming',
      reduce((context, event) => {
        return {
          ...context,
          error: event.error
        };
      })
    )
  )
```

Using vim's relative line numbers made it easy-ish to figure out the line numbers too, as long as the cursor is on the line above the first line of real code.

**Comment by octref** [comment]
This is already implemented with the latest highlight line API.

**Comment by danilopolani** [comment]
@octref thank you! Where can we find that API/Docs?

**Comment by danilopolani** [comment]
> @danilopolani Sorry it's a bit undocumented yet, but the options is added here: #259. I'll do some updates on docs soon.

Don't worry, that's a great news anyway :) Thank you!

**Comment by sokolenkov** [comment]
> This is already implemented with the latest highlight line API.

Where we can find the docs for highlight the line API ?

**Comment by digitigradeit** [comment]
> @dceddia Would you please provide the way you worked with Shiki and Jekyll? I am now configuring my Jekyll site, thanks.

There's a part 1 of a 2 part guide up which has a VERY VERY basic Jekyll plugin that invokes node to invoke Shiki then passes the code source code through stdin/stdout. It's not compatible with Github Pages however, so if you use another hosting platform such as Cloudflare Pages (which is essentially the same thing as Github Pages w/far fewer restrictions)... the plugin registers the {% shiki %} liquid tag so it wont conflict with built-in rouge. i even posted a comparison between shiki (obvously superior) compared to vs code (a screenshot) (identical) and the same code highlighted in highlight.js as well as the built-in route as well. LMK if you encounter any challenges 

https://brianjohnson.io/guides/2023-08-16-how-to-use-shiki-syntax-highlighting-in-jekyll/
