### ISSUE TITLE
API for hyperlinking

### ISSUE THREAD

**Issue by octref** [shikijs/shiki#79]
It would be awesome to link a specific text with an `<a>` tag.

**Comment by octref** [comment]
Part of #5.

**Comment by nathanclevenger** [comment]
@octref is this really a duplicate of #5? 

As I read that issue, the syntax requires setting a base URL and line numbers.  For most of my use cases, the links could be on any line and be of any domain.  I think that a dedicated syntax to detect links would be much preferable unless the scope of #5 is changed so that base URL and line numbers are optional.
