### ISSUE TITLE
Latest update to oniguruma-to-es@0.4.1 introduces weaker dependency tree

### ISSUE THREAD

**Issue by AndrewMohawk** [shikijs/shiki#843]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

The PR, https://github.com/shikijs/shiki/pull/836 bumps oniguruma-to-es from 0.1.2 to 0.4.1 by https://github.com/slevithan
and that in turn introduced some fairly unused packages ( emoji-regex-xs regex-utilities and regex-recursion) :
https://socket.dev/npm/package/regex-recursion/overview/4.2.1 // https://github.com/slevithan/regex-recursion
https://socket.dev/npm/package/regex-utilities/overview/2.3.0 // https://github.com/slevithan/regex-utilities 
https://socket.dev/npm/package/emoji-regex-xs/overview/1.0.0 // https://github.com/slevithan/emoji-regex-xs

These packages are all very unused right now and maintained by a single person ( @slevithan )  . While that might be okay it does open up some security concerns that there is a single point of failure here for a library (shiki) that is heavily used in the javascript ecosystem (2.4M weekly downloads).

I think it should be reviewed and the build processes evaluated as well as access controls for such a large dependency

### Reproduction

This can be reviewed at https://socket.dev/npm/package/shiki

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by slevithan** [comment]
Framing this around `oniguruma-to-es`'s small dependencies doesn't make much sense to me because they are created and maintained by the same author (me) as `oniguruma-to-es`, and were developed in large part to support `oniguruma-to-es`/Shiki.

- Yes, `oniguruma-to-es` is new and was created by one person (me), just as `oniguruma-to-js` (which it replaced) was created by one person (@antfu). I created it mostly for Shiki, after extensive discussion with @antfu and after he'd already incorporated my [Regex+](https://github.com/slevithan/regex) library into Shiki.
- My work is not new to the JS open source ecosystem, and I am among the deepest regex experts in the JS community (which is necessary for a project like this, and is why `oniguruma-to-es` is extremely robust despite being new). Although I've created the packages we're discussing this year, I've been releasing and maintaining heavily used open source JS libraries since 2007. E.g. my [XRegExp](https://github.com/slevithan/xregexp) package has over 14M monthly downloads (historically over 30M), and [parseUri](https://github.com/slevithan/parseuri) has over 1M (historically over 20M).
- `emoji-regex-xs` is cross-linked/endorsed by the author of `emoji-regex`, which has > 130M monthly downloads. Its author was also historically a major contributor to my XRegExp library.
- `regex-utilities` and `regex-recursion` are not expected to be used widely beyond the libraries they support: `oniguruma-to-es` and Regex+. Despite being relatively new, Regex+ has significant usage (and contribution) beyond Shiki.

Of course I'd welcome extra quality/security scrutiny and greater outside contributions for the libraries I maintain. However, there is no "single point of failure" as you described since the code we're discussing is MIT licensed.

**Comment by AndrewMohawk** [comment]
Heya @slevithan ,

No part of this is to criticize you or your work which seems *very valuable* to the community. Its more that if your account is compromised here it will impact a huge swath of js surface area.  As someone who is responsible for security I need to balance the risks of the things we include as dependencies. I think that with more usage and contributors/maintainers the risk profile does definitely go down!

-AM

**Comment by slevithan** [comment]
No worries, @AndrewMohawk! I didn't take it as criticism, although I realize my response might have come across as overly defensive. But I do think a by-the-numbers approach to risk assessment, without taking context into account, can lead to emphasizing the wrong things and can disincentivize use of modern libraries and modular design that benefits the ecosystem.

This issue singled out specific dependencies, rather than being a call for processes to harden Shiki in general. Describing those dependencies as "very unused" and "maintained by a single person" when they are small and essentially purpose-built for the libraries they support, feels like it's missing relevant context. I find alerts like [this](https://socket.dev/npm/package/@shikijs/engine-javascript/alerts/1.23.1?tab=dependencies) especially unhelpful: calling out `emoji-regex-xs` as a "possible typosquat attack" of `emoji-regex`, when in fact `emoji-regex`/`emoji-regex-xs` are libraries that promote each other, and there are very good reasons for using `emoji-regex-xs` in Shiki's context (it is 0.3KB compared to `emoji-regex`'s ~13KB uncompressed, and also higher performance).

**Comment by AndrewMohawk** [comment]
Totally, thats definitely a false positive and will be resolved hopefully soon once they see the usage go up! I will also report it as not type squatting! 

If there is something that can mitigate your account being compromised being a critical in the flow that would be awesome (ie, multi-party approval, maybe from @antfu as well).

**Comment by antfu** [comment]
It's definitely a false positive on Socket side. I don't know how to claim that repo and dismiss those issues.

Dependencies shouldn't be measured solely by stats. I see this problem related to people much more than numbers/algorithms. On that page, I trust @slevithan work as much as people should trust me personally.

Thanks for bringing this up. But I see there is no action required on our side.

**Comment by AndrewMohawk** [comment]
Then I think the expectation here is that everyone accepts that if @slevithan 's GH account gets compromised everyone in this project is at risk. If you were looking to mitigate some risk:
- Multi party approval for releases
- Ensuring phishing resistant MFA is on by default for all developers involved

**Comment by antfu** [comment]
Yes, but **anyone**'s GH account gets compromised, this would happen. While I agree that it would be better for projects to have multiple, let's admit that there are not enough open-source resources for every project. We can't blindly trust random contributors to have them on time for the sake of that. In very vertical fields, there might not ever be enough contributors coming in.

> MFA/Passwords manager

Please trust each individual has their security set up; no one wants to have their account hacked either. I believe you commented with goodwill, but let's not babysit on this
